---
title: "Math 189: Midterm Project 1"
output: pdf_document
---

#  Motor Trend Car Road Tests 

Working alone, prepare a R Markdown Notebook report based on examining the Motor Trend Car Road Tests dataset (available from GitHub). The file contains data extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models). The dataset contains 32 observations on 11 variables. 

## Analysis

What is the relationship between weight (wt) and miles per gallon (mpg)? Does this relationship depend on the number of cylinders (cyl)?

## Components to Your Report

This is your report, but consider including the following:

1. Introduction, Body, and conclusion.
2. Data citation.
3. Any relevant tools learned in lectures 1 through 6. Don't you want to use sample mean, sample variance, and sample correlation?
4. Justify your analysis. Are your estimators unbiased? Explain it to an engineer.

## Ethics

*Work alone!!!*

## Submission

Write an rmd file, render to pdf and submit the pdf.



