---
title: "Math 189 Schedule"
author: "Tucker McElroy"
date: "12/28/2020"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Schedule
Each 50-minute lesson will cover theoretical material in an R Markdown Notebook (which will be posted on Canvas and GitHub), allowing us to click through code that demonstrates the methodology. Below is a plan for topics (subject to change according to class pace):

1. **Introduction** (January 4, 2021) Policies and course goals.  Discussion of languages (R and Python), IDE (RStudio and PyCharm), generating reports (R Markdown), and GitHub.  Demo with Weekly Claims.
2. **Matrix Algebra** (January 6, 2021) Multivariate Data Intro.
3. **Exploratory Data Analysis I** (January 8, 2021)  Loading, Visualizing, Cleaning.
4. **Exploratory Data Analysis II** (January 11, 2021)  Random vectors, Central tendency.
5. **Exploratory Data Analysis III** (January 13, 2021)  Dispersion, Correlation.
6. **Multivariate Mean I** (January 15, 2021) Inference for Mean, Central Limit Theorem.    
7. **MLK Holiday** (January 18, 2021)  No Class!
8. **Multivariate Mean II** (January 20, 2021) Hypothesis Testing, Inference, Decision Rules.
9. **Multiple Testing I** (January 22, 2021) Family-Wise Error Rate, False Discovery Rate.
10. **Multiple Testing II** (January 25, 2021) Two-sample Mean Testing, Paired Samples.  *Mid-Term 1 Due*
11. **Multiple Testing III** (January 27, 2021) Unpaired Samples, Many Populations.
12. **Multivariate Analysis of Variance I** (January 29, 2021)  ANOVA, Total Sums of Squares.
13. **Multivariate Analysis of Variance II** (February 1, 2021) Wilks' Lambda, Pillai's Trace, Roy's Maximum Root.
14. **Classification via Discriminant Analysis I** (February 3, 2021) Classification, Conditional Probability, Bayes' Rule.
15. **Classification via Discriminant Analysis II** (February 5, 2021) LDA Procedure.
16. **Logistic Regression I** (February 8, 2021)  Logistic Model.
17. **Logistic Regression II** (February 10, 2021)  Multiple Logistic Regression.
18. **Support Vector Machine I** (February 12, 2021) Maximal Margin Classifier, Feature Space.
19. **President's Day Holiday** (February 15, 2021) No Class! *Mid-Term 2 Due* 
20. **Support Vector Machine II** (February 17, 2021)  Kernel, ROC Curve.
21. **Principal Components Analysis I** (February 19, 2021) High-dimensional Data, Dimension Reduction, Principal Components.
22. **Principal Components Analysis II** (February 22, 2021) Spectral Decomposition, Scree Plot.
23. **Factor Analysis I** (February 24, 2021) Latent Factors, Factor Loadings.
24. **Factor Analysis II** (February 26, 2021) Factor Model, Factor Scores.
25. **Resampling I** (March 1, 2021) Training Error, Validation.
26. **Resampling II** (March 3, 2021) K-fold Cross Validation
27. **Time Series I** (March 5, 2021) Cycles, Spans, Transformations.
28. **Time Series II** (March 8, 2021) Time Series Regression, Autoregression.
29. **Time Series III** (March 10, 2021) Nonparametric Regression, Moving Average Filters, Smoothers. 
30. **Time Series IV** (March 12, 2021) Forecasting, Conditional Heteroscedasticity, Volatility Filtering.
  


  

