---
# title: "Math 189 Syllabus"
# author: "Tucker McElroy"
# date: "12/7/2020"
output: 
  html_document:
    keep_md: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 
## **MATH 189 Syllabus (Winter 2020)**

### **Exploratory Data Analysis and Inference** 
Lectures: MWF 4:00-4:50

Zoom Meeting ID: 

<!-- ### Course Catalog Description -->
<!-- An introduction to various quantitative methods and statistical techniques for analyzing data—in particular big data. Quick review of probability continuing to topics of how to process, analyze, and visualize data using statistical language R. Further topics include basic inference, sampling, hypothesis testing, bootstrap methods, and regression and diagnostics. Offers conceptual explanation of techniques, along with opportunities to examine, implement, and practice them in real and simulated data. -->

### Overview
The goal of the course is to both provide the theoretical foundation for common statistical methods and train undergraduate students in data analysis. The course material includes statistical inference, multivariate analysis, linear models, and bootstrap. Class time will be divided between lectures presenting new methods and demonstrations of examples in R (https://www.r-project.org/).

Students are expected to master the concepts described in class, and be able to apply this knowledge to data; finally, students are expected to create reports that summarize their findings. To that end, students are expected to understand, write, debug, and apply R code to analyze data.
 
### Prerequisites
MATH 18 or MATH 20F or MATH 31AH, and MATH 20C and one of BENG 134, CSE 103, ECE 109, ECON 120A, MAE 108, MATH 180A, MATH 183, MATH 186, or SE 125. Students who have not completed listed prerequisites may enroll with consent of instructor. The following concepts will be frequently encountered throughout this course: random variable, mean, variance, probability density function, cumulative distribution function, independence, covariance, correlation, covariate, vector, and matrix. 

### Learning Outcomes
At the completion of the course, students will acquire the following skills:

1. Understand and speak the basic language of statistics
2. Appreciate the strengths and limitations of different methods, and formulate conclusions accordingly
3. Perform statistical data analysis 
4. Formulate conclusions in a statistical report (e.g. R Markdown)
5. Learn to use open source software (R) for data analysis

### Instructor
 Tucker S. McElroy
 
 Office Hours: ???
 
 email:  tmcelroy@ucsd.edu
 
 Phone: 240-695-3610
 
 Tucker S. McElroy is Senior Time Series Mathematical Statistician at the U.S. Census Bureau, where he has contributed to developing time series research and software for the last 17 years. Before Census, Tucker was a faculty fellow at UCSD, after receiving his PhD in mathematics in 2001. 

### Text
There is no required text.  The lecture notes (which are R Markdown Notebooks) are the primary course material. The following optional references may be useful:

1. *Exploratory Data Analysis with R*, by Roger D. Peng.  Also available at https://bookdown.org/rdpeng/exdata/
2. *R Programming for Data Science*, by Roger D. Peng.  A 2015 version is available from
https://math189.edublogs.org/files/2016/01/R-programming-for-Data-Science-2iehm2j.pdf
3. *An Introduction to Statistical Learning with Applications in R*, by G. James, D. Witten, T.
Hastie & R. Tibshirani. https://www.springer.com/us/book/9781461471370
4. *Applied Multivariate Statistical Analysis (4th edition)*, by Wolfgang K. Hardle & L.Simar.
https://www.springer.com/gp/book/9783540722441
 
### Grading
40% homework, 30% midterm project, 30% final project.

*Homework*: Students will work in groups of 3 to 5, collaborating to prepare a single R Markdown report. Do not collaborate with students outside your group! Each assignment involves some data analysis. There will be an assignment every week, due on Friday midnight.

*Projects*: Students will work alone on both a midterm and a final project, analyzing a data set and summarizing results in an R Markdown report.

### Course materials
All the lecture notes and class information will be available on Canvas, as well as the instructor's GitHub: https://github.com/tuckermcelroy/ma189.  

<!-- We will be using Piazza for forum-type discussions throughout the quarter. All posts will be anonymous to the student users but not the TAs and the instructor. -->
 
### Course structure
The course is centered around various case studies, each of which involves a data set and various scientific questions for investigation. The instructor will use class time to teach statistical concepts, and illustrate using R.

- Visualize and summarize multivariate data sets
- Inference on multivariate means
- Multivariate analysis of variance
- Linear models: simple and multiple regression
- Classification: linear discriminate analysis, K-nearest neighbors, support vector machines
- Tree-based methods: decision trees, random forest, boosting
- Unsupervised learning: principal component analysis, clustering methods

<!-- 1. Case Study 1 Concepts: mean, variance, kurtosis, quantile-quantile plots, normal approximations -->
<!-- 2. Case study 2 Concepts: survey methodology, simple random and stratified sampling, confidence intervals, bootstrap, finite sample population, confidence intervals, classification tree -->
<!-- 3. Case study 3 Concepts: poisson process, estimation and testing, goodness of fit test, two-sample testing, information, asymptotic variance -->
<!-- 4. Case study 4 Concepts: regression, longitudinal data, prediction, confidence intervals, testing -->

### Academic integrity
Discussions are encouraged in this class, and the group homeworks are collaborative. All students within a group are expected to participate substantially. There will be no sharing of homework between groups: copying or intentionally allowing students outside your group amounts to plagiarism. If such plagiarism occurs I will take the following action: a grade 0 will be assigned to all involved in the incident, and I will report the incident to the Academic Senate, which will then decide the appropriate course of action. 